GET http://localhost:5000/users/todo
###
GET http://localhost:5000/users/123

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "jgarcia",
    "password": "qwerty",
    "fullname": "José García",
    "email": "jg@example.com",
    "role": "subscriber"
}


###

PUT http://localhost:5000/users/123


###

DELETE http://localhost:5000/users/123


###

GET http://localhost:5000/posts

### 

PUT http://localhost:5000/users/63e1446b9c1e3cc5a2fb4e07

###

DELETE http://localhost:5000/users/63e1446b9c1e3cc5a2fb4e07

###

POST http://localhost:5000/users/signin

{
    "username": "jgarcia",
    "password": "qwerty"
}

###

GET http://localhost:5000/users?username=tgomez

### 

POST http://localhost:5000/users/subscriber